name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - v4
  repository_dispatch:
    types:
      - Changes-in-Content

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
          submodules: "recursive" # Include submodules
          token: ${{ secrets.BLOG }} # Use your GitHub token here
      # Configure Git user for the workflow
      - name: Configure Git user
        if: github.event_name == 'repository_dispatch'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - name: Pull Submodules
        if: github.event_name == 'repository_dispatch'
        run: |
          git submodule update --remote content
          git add content
          git commit -am "Updated submodule content"
          git push
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
